# -*- coding: utf-8 -*-
"""iitkgp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cENgZQZTbzVg06Nhkfs70KosaHSzrZzy
"""

import pandas as pd
import numpy as np

df = pd.read_csv('./PricingData.csv')
print(df)

df.isna().sum() #30767

c=0
lst_Fair_1 = []
lst_Fair_2 = []
for i in range(30649):
  try:
    ab = df['Seat Fare Type 1'][i].split(',')
    ab = list(np.float64(ab))
    if len(ab) != 8:    ###   Assuming the total tyes of seats are 8.
      # print(ab)
      for j in range(len(ab), 8):
        ab.append('None')
    lst_Fair_1.append(ab)
    # print(lst_Fair_1)
  except:
    lst_Fair_1.append(['None', 'None', 'None', 'None', 'None', 'None', 'None', 'None'])
  #   lst_Fair_1.append('None', 'None', 'None', 'None')
  try:
      ab = df['Seat Fare Type 2'][i].split(',')
      ab = list(np.float64(ab))
      if len(ab) != 8:
        for j in range(len(ab), 8):
          ab.append('None')
      # print(ab)
      lst_Fair_2.append(ab)
      # print(lst_Fair_2)
  except:
      lst_Fair_2.append(['None', 'None', 'None', 'None', 'None', 'None', 'None', 'None'])
      c+=1
print(c)

# lst = np.array(lst)
# lst
lst_Fair_1 = np.array(lst_Fair_1)
lst_Fair_2 = np.array(lst_Fair_2)

print(lst_Fair_1.shape, lst_Fair_2.shape)
print(lst_Fair_1)
print(lst_Fair_2)

##  peparing the final list of two prices..

final_price_list = []

for i  in range(30649):
  final_price_list.append([lst_Fair_1[i], lst_Fair_2[i]])

final_price_list = np.array(final_price_list)
print(final_price_list.shape)
print(final_price_list)

df.fillna(0)

import sklearn
from sklearn.manifold import TSNE

#  lst = np.array(lst)
#  lst = np.expand_dims(lst, -1)
#  X_embedded = TSNE(n_components=2, learning_rate='auto',
#                   init='random').fit_transform(lst)

# X_embedded.shape

output = pd.read_csv('./sample_output.csv')
output

output.isna().sum()

c=0
lst_Fair_1 = []
lst_Fair_2 = []
for i in range(30649):
  try:
    ab = df['Seat Fare Type 1'][i].split(',')
    ab = list(np.float64(ab))
    if len(ab) != 8:    ###   Assuming the total tyes of seats are 8.
      # print(ab)
      for j in range(len(ab), 8):
        ab.append(0)
    lst_Fair_1.append(ab)
    # print(lst_Fair_1)
  except:
    lst_Fair_1.append([0,0,0,0,0,0,0,0])
  #   lst_Fair_1.append('None', 'None', 'None', 'None')
  try:
      ab = df['Seat Fare Type 2'][i].split(',')
      ab = list(np.float64(ab))
      if len(ab) != 8:
        for j in range(len(ab), 8):
          ab.append(0)
      # print(ab)
      lst_Fair_2.append(ab)
      # print(lst_Fair_2)
  except:
      lst_Fair_2.append([0,0,0,0,0,0,0,0])
      c+=1
print(c)

# lst = np.array(lst)
# lst
lst_Fair_1 = np.array(lst_Fair_1)
lst_Fair_2 = np.array(lst_Fair_2)

from numpy import mean, std

mean = mean(lst_Fair_1)
print(np.var(lst_Fair_1))

